### ISSUE TITLE
Wallet addresses disappearing from start page for some users

### ISSUE THREAD

**Issue by Sphearis** [wavesplatform/wavesplatform.core.js#26]
Using Chrome Liteclient on Windows 10 makes the wallet addresses disappear from the liteclient starting page.
Data look like it is still there (not cleared) but I didn't find a way to get them working with the new wallet version.
This problem isn't an isolated one, I've got it on all 3 computers (including one at work) and some friends have the same issue. It could lead to unexpected loss of funds if people didn't save their seed correctly.

**Comment by beregovoy68** [comment]
Did you mean that after upgrade to Chrome App version 0.4.16 you encountered this issue?

**Comment by Sphearis** [comment]
It did on the 3 computers which were automatically updated to the newest version, a fourth one doesn't have this problem but it seems that one is not updated yet.

**Comment by beregovoy68** [comment]
Well, this behavior is correct. Let me explain why.
Google Chrome Apps are able to synchronize their storage between multiple devices. That's a really cool feature but works only for Chrome Apps and there is a strict limitation of 8Kb of data per record. That was enough for the first versions of Lite Client. Now we need to store some data about orders, favorite pairs, favorite assets and so on. That limitation has become a real problem. When you try to save some data you get the error that the quota is exceeded and data are not written. You can lose sensitive information in this case.

Moreover, Google is going to shutdown Chrome Apps in the near future that's why support of storage synchronization is pointless.

In your case your data are not lost. They're stored in your fourth device locally.
